# Generated by Django 2.2 on 2021-05-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
