# Generated by Django 2.2 on 2021-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0004_auto_20210515_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
