# Generated by Django 2.2 on 2021-05-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0005_auto_20210516_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('instructions', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_drink', to='RecipeApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drink_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_reviews', to='RecipeApp.Drink')),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Drinkreviews', to='RecipeApp.User')),
            ],
        ),
    ]
